/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RespondersRole;

import Business.ClaimsAccount.Claims;
import Business.Employee.Responders;
import Business.Employee.Volunteers;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;

import java.awt.CardLayout;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
/**
 *
 * @author yashk
 */
public class RespondersWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel container;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem system;
    private Organization organization;
    private Responders responders;
    private Volunteers volunteers;

    /**
     * Creates new form RespondersWorkAreaJPanel
     */
    public RespondersWorkAreaJPanel(JPanel container, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        
        this.container = container;
        this.enterprise = enterprise;
        this.organization = organization;
        this.userAccount = account;
        this.system = system;
        this.responders = account.getResponders();
        valueLabel.setText(enterprise.getName());
        
        if(responders.getFinalizedVolunteers()!= null){
        this.volunteers = responders.getFinalizedVolunteers();
        
        populateVolunteersDetails();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewVolunteersJButton = new javax.swing.JButton();
        updateProfile = new javax.swing.JButton();
        btnCreateClaims = new javax.swing.JButton();
        btnCreateInsurance = new javax.swing.JButton();
        viewBankDetails = new javax.swing.JButton();
        chkInsurance = new javax.swing.JRadioButton();
        chkBankAccount = new javax.swing.JRadioButton();
        btnRefresh = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblName2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblAddress2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblContact2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblEmail2 = new javax.swing.JLabel();
        volunteersImg2 = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        valueLabel2 = new javax.swing.JLabel();

        viewVolunteersJButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        viewVolunteersJButton.setText("Volunteers");
        viewVolunteersJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewVolunteersJButtonActionPerformed(evt);
            }
        });

        updateProfile.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        updateProfile.setText("View/Update Profile");
        updateProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProfileActionPerformed(evt);
            }
        });

        btnCreateClaims.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnCreateClaims.setText("Create Claims Request");
        btnCreateClaims.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateClaimsActionPerformed(evt);
            }
        });

        btnCreateInsurance.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnCreateInsurance.setText("Insurance ");
        btnCreateInsurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateInsuranceActionPerformed(evt);
            }
        });

        viewBankDetails.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        viewBankDetails.setText("View Bank Details");
        viewBankDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBankDetailsActionPerformed(evt);
            }
        });

        chkInsurance.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        chkInsurance.setText("Insurance");
        chkInsurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkInsuranceActionPerformed(evt);
            }
        });

        chkBankAccount.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        chkBankAccount.setText("Claims Request");
        chkBankAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBankAccountActionPerformed(evt);
            }
        });

        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("VOLUNTEER :");

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(64, 151, 182));
        jLabel13.setText("NAME:");

        lblName2.setText("TBP");

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(64, 151, 182));
        jLabel14.setText("ADDRESS:");

        lblAddress2.setText("TBP");

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(64, 151, 182));
        jLabel15.setText("CONTACT:");

        lblContact2.setText("TBP");

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(64, 151, 182));
        jLabel16.setText("EMAIL:");

        lblEmail2.setText("TBP");

        volunteersImg2.setBackground(new java.awt.Color(102, 255, 102));
        volunteersImg2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(lblName2)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(lblAddress2)
                    .addComponent(lblContact2)
                    .addComponent(lblEmail2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(volunteersImg2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(volunteersImg2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblName2)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAddress2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addGap(5, 5, 5)
                        .addComponent(lblContact2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEmail2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        valueLabel.setFont(new java.awt.Font("Lucida Grande", 3, 24)); // NOI18N
        valueLabel.setText("<value>");

        valueLabel2.setFont(new java.awt.Font("Lucida Grande", 3, 24)); // NOI18N
        valueLabel2.setText("ENTERPRISE:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(572, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(valueLabel2)
                        .addGap(65, 65, 65)
                        .addComponent(valueLabel)
                        .addGap(84, 84, 84)
                        .addComponent(btnRefresh)
                        .addGap(317, 317, 317))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(chkBankAccount)
                            .addGap(159, 159, 159)
                            .addComponent(chkInsurance))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(viewVolunteersJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCreateClaims, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(71, 71, 71)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnCreateInsurance, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(updateProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(viewBankDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(125, 125, 125)))
                    .addContainerGap(893, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(valueLabel)
                            .addComponent(valueLabel2))))
                .addGap(34, 34, 34)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(280, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(viewVolunteersJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(updateProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(114, 114, 114)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chkBankAccount)
                        .addComponent(chkInsurance))
                    .addGap(58, 58, 58)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCreateClaims, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCreateInsurance, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(70, 70, 70)
                    .addComponent(viewBankDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(210, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewVolunteersJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewVolunteersJButtonActionPerformed
       if(responders.getAddress() == null){
            JOptionPane.showMessageDialog(this, "Please update the document before viewing volunteers");
            return;
        }
        else{
            if(responders.getFinalizedVolunteers()== null)
            {

                CardLayout layout = (CardLayout) container.getLayout();
                container.add("ViewVolunteersDirectory", new VolunteersDirectory(container, userAccount, responders,enterprise));
                layout.next(container);
            }
            else{
                JOptionPane.showMessageDialog(this, "You are already set, cant view volunteers. \n Please contact your claims manager!");
                return;
            }
       }
    }//GEN-LAST:event_viewVolunteersJButtonActionPerformed

    private void updateProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProfileActionPerformed

        CardLayout layout = (CardLayout) container.getLayout();
        RespondersProfile respondersProfile = new RespondersProfile(userAccount,organization, container);
        container.add(respondersProfile);
        layout.next(container);
    }//GEN-LAST:event_updateProfileActionPerformed

     private void populateVolunteersDetails(){
        lblName2.setText(volunteers.getFirstName() +" "+ volunteers.getLastName());
        lblAddress2.setText(volunteers.getAddress());
        lblContact2.setText(volunteers.getContactVolunteers());
        volunteersImg2.setIcon(new ImageIcon(volunteers.getImgPath()));
    }
    
    private void btnCreateClaimsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateClaimsActionPerformed
       if(userAccount.getResponders().getTypeL() != 2){
            CardLayout layout = (CardLayout) container.getLayout();
            //LoanCreation bankAcc = new LoanCreation();
            ClaimsRequest bankAcc = new ClaimsRequest(userAccount, container, system);
            container.add(bankAcc);
            layout.next(container);
        }
        else{
            JOptionPane.showMessageDialog(this, "Cant select Loan as your Bank account is not ready or else you have opted for Insurance");
            return;
        }
    }//GEN-LAST:event_btnCreateClaimsActionPerformed

    private void btnCreateInsuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateInsuranceActionPerformed
        if(userAccount.getResponders().getTypeL() != 1){
            CardLayout layout = (CardLayout) container.getLayout();
            InsuranceDetails bankAcc = new InsuranceDetails(userAccount, container, enterprise, system);
            container.add(bankAcc);
            layout.next(container);
        }
        else{
            JOptionPane.showMessageDialog(this, "Cant select Insurance as your Bank account is not ready or else you have opted for Loan");
            return;
        }
    }//GEN-LAST:event_btnCreateInsuranceActionPerformed

    private void viewBankDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBankDetailsActionPerformed
       
         if(responders.getClaimsaccount().getClaimsAccountNumber() == 0){
            JOptionPane.showMessageDialog(this, "Please wait for AID Manager to accept the bank account req");
            return;
        }
        else{
            CardLayout layout = (CardLayout) container.getLayout();
            UpdateBankDetails bankAcc = new UpdateBankDetails(userAccount, container, system);
            container.add(bankAcc);
            layout.next(container);
        }
    }//GEN-LAST:event_viewBankDetailsActionPerformed

    private void chkInsuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkInsuranceActionPerformed
        if(responders.getClaimsaccount().getClaimsAccountNumber() == 0){
            JOptionPane.showMessageDialog(this, "Please wait for AID Manager to accept the AID account req");
            return;
        }
        if(responders.getVolunteersAidfund() == 0){
            JOptionPane.showMessageDialog(this, "Please wait for volunteers to add aid amount");
            return;
        }
        if(responders.getOwnFunds() == 0){
            JOptionPane.showMessageDialog(this, "Please add your contribution in View claim Acccount page");
            return;

        }

        if (chkBankAccount.isSelected()){
            btnCreateClaims.setEnabled(false);
            btnCreateInsurance.setEnabled(true);
            chkInsurance.setSelected(false);
        }
    }//GEN-LAST:event_chkInsuranceActionPerformed

    private void chkBankAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBankAccountActionPerformed
        if(responders.getClaimsaccount().getClaimsAccountNumber() == 0){
            JOptionPane.showMessageDialog(this, "Please wait for AID Manager to accept the AID account req");
            return;
        }
        if(responders.getVolunteersAidfund() == 0){
            JOptionPane.showMessageDialog(this, "Please wait for volunteers to add aid amount");
            return;
        }
        if(responders.getOwnFunds() == 0){
            JOptionPane.showMessageDialog(this, "Please add your contribution in View claim Acccount page");
            return;

        }

        if (chkBankAccount.isSelected()){
            btnCreateClaims.setEnabled(true);
            btnCreateInsurance.setEnabled(false);
            chkInsurance.setSelected(false);
        }
    }//GEN-LAST:event_chkBankAccountActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        if(responders.getFinalizedVolunteers()!= null){
        this.volunteers = responders.getFinalizedVolunteers();
        
        populateVolunteersDetails();
        }
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateClaims;
    private javax.swing.JButton btnCreateInsurance;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JRadioButton chkBankAccount;
    private javax.swing.JRadioButton chkInsurance;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblAddress2;
    private javax.swing.JLabel lblContact2;
    private javax.swing.JLabel lblEmail2;
    private javax.swing.JLabel lblName2;
    private javax.swing.JButton updateProfile;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JLabel valueLabel2;
    private javax.swing.JButton viewBankDetails;
    private javax.swing.JButton viewVolunteersJButton;
    private javax.swing.JLabel volunteersImg2;
    // End of variables declaration//GEN-END:variables
}
